### PR TITLE
Create lib jar file

### PR DESCRIPTION
**Pull request by vincent-karuri**
Configure opensrp-server-openlmis to build  a jar file that can be imported into, among others, the OpenSRP server.

See issue #8

### CODE REVIEW

**Comment by githengi** [comment]
Some endpoints e.g dispensable, trade items, commodity types are not returning server versions on the get or sync endpoints

**Comment by vincent-karuri** [comment]
Having update and add on the same endpoint is not a good api design practice. POST should not be used to update as a convention.

`... incase OpenLMIS is not being used`

Could you explain what this means?

**Comment by vincent-karuri** [comment]
I have updated the json data and removed the server version when posting. Try using that data instead. Server versions show for me.

**Comment by githengi** [comment]
Batch POST endpoints do not update data.

**Pull request merged**
